# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BingoGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bingo(object):
    def setupUi(self, Bingo):
        Bingo.setObjectName("Bingo")
        Bingo.resize(1020, 765)
        self.centralwidget = QtWidgets.QWidget(Bingo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../GIF/39f6a005763b37e2237b320df0e68e31.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 421, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../GIF/T8bahf.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 570, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transperent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 640, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transperent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 600, 151, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 600, 151, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setObjectName("pushButton_2")
        Bingo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Bingo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menubar.setObjectName("menubar")
        Bingo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Bingo)
        self.statusbar.setObjectName("statusbar")
        Bingo.setStatusBar(self.statusbar)

        self.retranslateUi(Bingo)
        QtCore.QMetaObject.connectSlotsByName(Bingo)

    def retranslateUi(self, Bingo):
        _translate = QtCore.QCoreApplication.translate
        Bingo.setWindowTitle(_translate("Bingo", "MainWindow"))
        self.pushButton.setText(_translate("Bingo", "Start"))
        self.pushButton_2.setText(_translate("Bingo", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bingo = QtWidgets.QMainWindow()
    ui = Ui_Bingo()
    ui.setupUi(Bingo)
    Bingo.show()
    sys.exit(app.exec_())
